/**
 * Default index.astro Template
 * Wird erstellt wenn neues ttEditor-Projekt initialisiert wird
 */

export function getDefaultAstroTemplate(projectName: string): string {
  const timestamp = new Date().toISOString();

  return `---
// Generated by TT-Editor Low-Code Extension
// Project: ${projectName}
// Created: ${timestamp}

// Import Layout and Components
import Layout from "@/layouts/Layout.astro";
// import Input from "@components/SimpleInput.astro";
// import Field from "@components/SimpleFieldset.astro";
// ... weitere Imports nach Bedarf
---

<Layout>
  <h1>${projectName}</h1>
  <p>Dieses Projekt wurde mit dem TT-Editor Low-Code Extension erstellt.</p>

  <!-- Canvas-generierte Komponenten werden hier eingefügt -->
</Layout>
`;
}
