// src/ui/src/utils/astroCodeGen.ts

import type { ComponentNode } from '../../../shared/messageProtocol';

/**
 * Rendert eine einzelne Node zu Astro-Code
 *
 * FEATURES (DEUTSCH):
 * - Formatiert Props (filtert empty/false/null/undefined)
 * - Boolean Props ohne Wert (required statt required="true")
 * - Rekursive Children mit Einrückung
 * - Self-closing wenn keine Children
 *
 * EXAMPLE:
 * Input:  { type: 'SimpleInput', props: { id: 'email', required: true, hidden: false } }
 * Output: <SimpleInput id="email" required />
 *
 * @param node - Die zu rendernde ComponentNode
 * @param depth - Aktuelle Verschachtelungstiefe (für Einrückung)
 * @returns Formatierter Astro-Code als String
 */
export function renderAstro(node: ComponentNode, depth: number = 0): string {
  const indent = '  '.repeat(depth);

  // Verwende compName falls vorhanden, sonst type
  const tagName = node.compName || node.type;

  // Format props (filter falsy values)
  const props = Object.entries(node.props || {})
    .filter(([_k, v]) => v !== '' && v !== false && v !== null && v !== undefined)
    .map(([k, v]) => {
      if (typeof v === 'boolean') return k; // Boolean without value
      // Escape double quotes in attribute values
      const escapedValue = String(v).replace(/"/g, '&quot;');
      return `${k}="${escapedValue}"`;
    })
    .join(' ');

  // Recursive children
  const children = (node.children || [])
    .map((c) => renderAstro(c, depth + 1))
    .join('\n');

  // Self-closing or with children
  if (children) {
    const propsStr = props ? ' ' + props : '';
    return `${indent}<${tagName}${propsStr}>\n${children}\n${indent}</${tagName}>`;
  }

  const propsStr = props ? ' ' + props : '';
  return `${indent}<${tagName}${propsStr} />`;
}

/**
 * Generiert eine vollständige Astro-Datei aus dem Tree
 *
 * STRUCTURE (DEUTSCH):
 * - Frontmatter (---)
 * - HTML Boilerplate
 * - Body mit generierten Komponenten (depth = 1)
 *
 * LIMITATION (DEUTSCH):
 * - Keine Import-Statements (müssen manuell hinzugefügt werden)
 * - Kein Layout-System (muss manuell integriert werden)
 * - Minimales Template für Prototyping
 *
 * @param tree - Array von Root-Level ComponentNodes
 * @param projectName - Projektname für Title und Kommentar
 * @returns Vollständiger Astro-Dateiinhalt als String
 */
export function generateAstroFile(tree: ComponentNode[], projectName: string): string {
  const components = tree.map((node) => renderAstro(node, 2)).join('\n');

  return `---
// ${projectName} - Generated by ttEditor
---

<html>
  <head>
    <title>${projectName}</title>
  </head>
  <body>
${components}
  </body>
</html>
`;
}
